#!/usr/bin/perl
@letters = ("e", "a", "c", "b", "d");
print @letters;
print "\n";
@numbers = (4..9);
@letters = sort(@letters);
print @letters;
$size = @numbers;
print "\n";
print $size . "\n";
@sNum = sort{$b <=> $a}@numbers;
print @sNum;
print "\n";
print @numbers;
print "\n";
push(@letters, $numbers[0]);
print @letters;
print "\n";
$last = pop(@numbers);
unshift(@letters, $last);
print @letters;
print "\n";
splice(@letters, 2,0,1);
print @letters;
print "\n";
splice(@letters, 4,2,2..3);
print @letters;
print "\n";
$string = join('-', @letters);
print $string;
print "\n";
@arrayString = split('-', $string, 4);
print @arrayString;
print "\n";
@arrayString = split('-', $string);
print @arrayString;
print "\n";
@mergeArrays = (@letters, @numbers);
print @mergeArrays;

